In [1]:
import numpy as np

In [2]:
# 创建一维数组
a = np.array([1,2,3,4,5])

In [4]:
# 创建二维数组
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

## 获取矩阵的行数列数

In [5]:
print(a2.shape)# 结果返回一个tuple元组(2L, 5L)

(2, 5)


In [6]:
print(a2.shape[0]) # 获得行数，返回

2


In [7]:
print(a2.shape[1]) #获得列数，返回

5


## 矩阵截取

### 按行列截取

In [9]:
print(a２[0:1]) # 截取第一行，返回

[[1 2 3 4 5]]


In [11]:
print(a2[1,2:5]) # 截取第二行，第三四列，返回

[ 8  9 10]


In [12]:
print(a2[1,:]) # 截取第二行，返回

[ 6  7  8  9 10]


### 按条件截取

In [14]:
b = a2[a2>6] # 截取矩阵a2中大于6 的元素，返回一维数组
print(b)

[ 7  8  9 10]


In [15]:
# 其实布尔语句首先生成一个布尔矩阵，将布尔矩阵传入[]实现截取
print(a2>6)

[[False False False False False]
 [False  True  True  True  True]]


按条件截取应该较多的是对矩阵中满足一定条件的元素变成特定的值。例如将矩阵中大于6的元素变成0

In [18]:
a2[a2>6] = 0
print(a2)

[[1 2 3 4 5]
 [6 0 0 0 0]]


### 矩阵的合并

矩阵的合并可以通过numpy中的hstack方法和vstack方法实现

In [20]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [22]:
# !注意　参数传入时要以列表list或元组tuple的形式传入
print(np.hstack([a1,a2])) # 横向合并

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
print(np.vstack((a1,a2))) # 纵向合并

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


矩阵的合并也可以通过 concatenate 方法

np.concatenate((a1,a2),axis=0) 等价于 np.vstack((a1,a2))  

np.concatenate((a1,a2),axis=1) 等价于 np.hstack((a1,a2))

### linspace

linspace() 和 matlab 的 linspace 很类似，用于创建指定数量等间隔的序列，实际生成一个等差数列

In [25]:
a = np.linspace(0,10,7) # 生成首位是0, 末位是10, 含 7 个数的等差数列
print(a)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


### logspace

logspace() 用于生成等比数列  

下面的例子是用于生成首位是 $10^0$, 末位是 $10^2$, 含 $5$ 个数的等比数列

In [26]:
a = np.logspace(0,2,5)
print(a)

[  1.           3.16227766  10.          31.6227766  100.        ]


### empty

empty 创建空矩阵(实际有值)

In [27]:
np.empty((3,4)) # 创建 $3\times 4$ 的空矩阵

array([[6.89891424e-310, 1.91383561e-316, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

### fromstring

fromstring() 方法可以将字符串转化为 ndarray　对象，需要将字符串数字化时这个方法比较有用，可以获得字符串的 ascii 码序列。

In [30]:
a = "abcdef"
b = np.fromstring(a,dtype=np.int8)# 因为一个字符为8位，所以指定dtype 是 np.int8

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


### fromfunction

fromfunction() 方法可以根据矩阵的行号列号生成矩阵的元素。  

例如创建一个矩阵，矩阵中的每个元素都为行号和列号的和。

In [32]:
def func(i,j):
    return i+j
a = np.fromfunction(func,(5,6)) # 第一个参数为指定函数，第二个参数为列表list或元组tuple, 说明矩阵的大小
print(a)

[[0. 1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7. 8.]
 [4. 5. 6. 7. 8. 9.]]


### 矩阵的运算

#### 常用矩阵运算符

numpy 中的 ndarray 对象重载了许多运算符，使用这些运算符可以完成矩阵间对应元素的运算

'/' 矩阵对应元素相除，若都是整数则取商  

'%' 矩阵对应元素相除后取余数

### 常用的矩阵函数

a 为ndarray 对象

|矩阵函数|说明|
|---|---|
|np.sin(a)|对矩阵a中的每一个元素取正弦|
|np.arcsin(a)|对矩阵a中每一个元素取反正弦|
|np.arctan(a)|对矩阵a　中的每一个元素取反正切|
|np.exp(a)|对矩阵a中的每一个元素取指数函数|

### 矩阵乘法(点乘)

矩阵乘法必须满足矩阵乘法的条件，即第一个矩阵的列数等于第二个矩阵的行数。　　

矩阵乘法的函数为dot

In [33]:
a1 = np.array([[1,2,3],[4,5,6]]) # a1 为　2*3 矩阵
a2 = np.array([[1,2],[3,4],[5,6]]) # a2是3*2的矩阵
print(a1.shape[1] == a2.shape[0]) # True 满足矩阵乘法的条件

True


In [34]:
print(a1.dot(a2))

[[22 28]
 [49 64]]


### 矩阵的转置

a.T