已知 reshape 函数可以由一维数组生成多维数组

+ revel 函数可以展平数组  

+ flatten() 函数也可以实现同样的功能

In [2]:
import numpy as np

In [3]:
a = np.arange(12)

In [9]:
b = a.reshape((4,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**注意:** ravel 只提供视图 view, 而 flatten 分配内存存储

### 数组属性

In [11]:
b.shape # 数组维度

(4, 3)

In [12]:
b.dtype # 元素类型

dtype('int64')

In [13]:
b.size # 数组元素个数

12

In [14]:
b.itemsize # 元素占用字节数

8

In [15]:
b.nbytes # 整个数组占用存储空间 = itemsize*size

96

In [16]:
b.T # 转置 = transpose

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [4]:
c = np.repeat(a,2)
c

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9,  9, 10, 10, 11, 11])